config/routes.rb
Rails.application.routes.draw do

  get '/' => 'home#index' # this is only used for devise > after change password > redirect

  # get 'logout/index'
  resources :logout, only: [:index]

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration' # change password without registration
    patch 'users' => 'devise/registrations#update', as: 'user_registration' # change password without registration
  end

  resources :home, only: [:index, :show]

  namespace :hq do
    resources :myc_programs, only: [:index, :index_data] do
      collection do
        post 'index_data'
      end
    end

    resources :users do
      collection do
        post 'index_data'
      end
      member do
        get 'invite_confirm'
        patch 'invite'
        get 'edit_status'
        get 'set_profile' # after login
      end

      resources :teachers, only: [:new, :create, :edit, :update]
      resources :studio_users, only: [:index, :new, :create] do
        collection do
          post 'index_data'
        end
      end
    end

    resources :teachers, only: [:edit, :update]

    resources :studio_users, only: [:destroy] do
      member do
        get 'delete'
      end
    end

    resources :studios do
      collection do
        post 'data'
      end
    end

    resources :product_codes, except: [:delete, :show] do
      collection do
        post 'index_data'
      end
      member do
        post 'pack_data_by_code'
        get 'select_pack'
        post 'add_pack'
        get 'remove_pack_confirm/:product_pack_id', action: 'remove_pack_confirm'
        delete 'remove_pack/:product_pack_id', action: 'remove_pack'

        post 'item_data_by_code'
        get 'select_item'
        post 'add_item'
        get 'remove_item_confirm/:product_item_id', action: 'remove_item_confirm'
        delete 'remove_item/:product_item_id', action: 'remove_item'
        get 'show_pack_items/:product_pack_id', action: 'show_pack_items'
      end
    end

    resources :product_packs, except: [:delete, :show] do
      collection do
        post 'index_data'
      end
      member do
        post 'item_data_by_pack'
        get 'select_item'
        post 'add_item'
        get 'remove_item_confirm/:product_item_id', action: 'remove_item_confirm'
        delete 'remove_item/:product_item_id', action: 'remove_item'
      end

      resources :product_items, only: [:index]
    end

    resources :product_items, only: [:index, :new, :create, :edit, :update] do
      collection do
        post 'index_data'
      end
    end

    resources :student_reports, only: [:index] do
      collection do
        post 'index_data'
        post 'index_total_data'
        post 'generate'
      end
    end
  end

  namespace :myc do
    resources :calendar, only: [:index]

    resources :teachers, only: [:index] do
      collection do
        post 'index_data'
      end
    end

    resources :students, except: [:delete, :show] do
      collection do
        post 'index_data'
      end
    end

    resources :myc_classes, only: [:index, :new, :create, :show] do
      collection do
        post 'index_data'
        post 'new_students_data'
        post 'old_students_data'
        post 'in_class_students_data'
        post 'student_attendance_data'
      end

      member do
        get 'choose_students_to_add'
        post 'add_students'

        get 'choose_student_to_remove'
        post 'check_student_attendance'
        post 'remove_student'

        get 'dissolve_confirm'
        patch 'dissolve'

        get 'undo_dissolve_confirm'
        patch 'undo_dissolve'
      end
    end

    resources :lessons do
      member do
        get 'choose_teacher_to_change'
        post 'change_teacher'

        get 'set_data_for_lesson_make_up/:make_up_type', action: 'set_data_for_lesson_make_up'
        post 'lesson_make_up'

        get 'choose_students_to_mark_attendance'
        post 'mark_attendance'

        get 'unmark_attendance_confirm'
        patch 'unmark_attendance'
      end
    end

    resources :families, except: [:delete] do
      collection do
        post 'index_data'
      end
    end

    resources :holidays, except: [:delete]  do
      collection do
        post 'index_data'
      end
    end

    resources :invoices, except: [:delete]  do
      resources :invoice_items, only: [:destroy] do
        collection do
          post 'index_data'
        end
        member do
          get 'delete', action: 'delete'
        end
      end

      collection do
        post 'index_data'
        post 'invoice_new_student_data'
        post 'invoice_existing_student_data'

        get 'choose_student', action: 'choose_student'
        post 'add_new_student', action: 'add_new_student'
        post 'add_existing_student', action: 'add_existing_student'

        get 'fee_item/program', action: 'program'
        get 'fee_item/discount', action: 'discount'
        get 'fee_item/lesson', action: 'lesson'
        post 'material_data', action: 'material_data'

      end
      member do
        get 'fee_item/program', action: 'program'
        get 'fee_item/discount', action: 'discount'
        get 'fee_item/lesson', action: 'lesson'
        get 'fee_item/material', action: 'material'
        get 'fee_item/other', action: 'other'

        post 'program_fee_item_data', action: 'program_fee_item_data'
        post 'discount_fee_item_data', action: 'discount_fee_item_data'
        post 'lesson_fee_item_data', action: 'lesson_fee_item_data'
        post 'add_program_fee_item', action: 'add_program_fee_item'
        post 'add_discount_fee_item', action: 'add_discount_fee_item'
        post 'add_lesson_fee_item', action: 'add_lesson_fee_item'
        post 'add_material_fee_item', action: 'add_material_fee_item'
        post 'add_other_fee_item', action: 'add_other_fee_item'
      end
    end

    resources :teacher_commissions, only: [:index, :show, :edit, :update] do
      collection do
        post 'index_data'
        post 'show_data'
        get 'generate_confirm'
        post 'generate'
      end
      resources :teacher_commission_items do
        collection do
          post 'index_data'
        end
        member do
          patch 'update_percentage'
          get 'edit_percentage'
          get 'edit_remarks'
        end
      end

      resources :teacher_commission_item_additionals, only: [:new, :create] do
        collection do
          post 'index_data'
        end
      end

      resources :teacher_commission_others, only: [:new, :create] do
        collection do
          post 'index_data'
        end
      end
    end

    resources :teacher_commission_item_additionals, only: [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :teacher_commission_others, only: [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end
  end


end

app/controllers/myc/calendar_controller.rb
class Myc::CalendarController < ApplicationController
  layout 'application'

  def index
    start_date = params['start']
    end_date = params['end']
    @holidays = Holiday.events_for_calendar(session[:current_studio_id], start_date, end_date)
    @lessons = Lesson.events_for_calendar(session[:current_studio_id], start_date, end_date)
  end
end

app/controllers/myc/families_controller.rb
class Myc::FamiliesController < ApplicationController
  def index_data
    respond_to do |format|
      format.html
      format.json { render json: FamilyDatatable.new(view_context, { studio_id: session[:current_studio_id] }) }
    end
  end

  def new
    session[:referrer] = request.referrer # set the previous url
    @family = Family.new
  end

  def create
    @family = Family.new(family_params.merge(:studio_id => session[:current_studio_id]))
    if @family.save
      flash[:success] = t('save_success')
      if session[:referrer] == nil
        redirect_to(action: 'index')
      else
        redirect_to(session[:referrer])
      end
      session.delete(:referrer)
    else
      flash[:error] = t('save_fail')
      render('new')
    end
  end

  def edit
    session[:referrer] = request.referrer
    @family = Family.find(params[:id])
  end

  def update
    @family = Family.find(params[:id])
    if @family.update_attributes(family_params)
      flash[:success] = t('save_success')
      if session[:referrer] == nil
        redirect_to(action: 'index')
      else
        redirect_to(session[:referrer])
      end
      session.delete(:referrer)
    else
      render('edit')
    end
  end

  def show
      @family = Family.find(params[:family_id])
      respond_to do |format|
      format.json { render :json => {:data => @family}, status: :ok }
      end
  end

  private
  def family_params
    params.require(:family).permit(
        :address1,
        :address2,
        :postal_code,
        :city_or_state,
        :country,
        :primary_contact_name,
        :primary_contact_relationship,
        :primary_contact_phone_no,
        :primary_contact_email,
        :primary_contact_occupation,
        :primary_contact_music_background,
        :primary_contact_accompany_for_student,
        :other_contact_name,
        :other_contact_relationship,
        :other_contact_phone_no,
        :other_contact_email,
        :other_contact_occupation,
        :other_contact_music_background,
        :other_contact_accompany_for_student,
        :status
    )
  end
end

app/controllers/myc/holidays_controller.rb
class Myc::HolidaysController < ApplicationController
  def index_data
    respond_to do |format|
      format.html
      format.json { render json: HolidayDatatable.new(view_context, { studio_id: session[:current_studio_id] }) }
    end
  end

  def index
  end

  def new
    @holiday = Holiday.new
  end

  def create
    @holiday = Holiday.new(holiday_params.merge(:studio_id => session[:current_studio_id]))
    if @holiday.save
      flash[:success] = t('save_success')
      redirect_to(:action => 'index')
    else
      flash[:error] = t('save_fail')
      render('new')
    end
  end

  def edit
    session[:referrer] = request.referrer
    @holiday = Holiday.find(params[:id])
    @holiday[:holiday_date] = @holiday.holiday_date.to_s
  end

  def update
    @holiday = Holiday.find(params[:id])
    if @holiday.update_attributes(holiday_params)
      flash[:success] = t('save_success')
      redirect_to(:action => 'index')
    else
      render('edit')
    end
  end

  private
  def holiday_params
    holiday_params = params.require(:holiday).permit(
        :holiday_date,
        :holiday_name,
    )
    holiday_params[:holiday_date] = to_date(holiday_params[:holiday_date])
    return holiday_params
  end
end

app/controllers/myc/invoice_items_controller.rb
class Myc::InvoiceItemsController < ApplicationController
  include ApplicationHelper
  def index_data
    respond_to do |format|
      format.html
      format.json { render json: InvoiceItemDatatable.new(view_context, { invoice_id: params[:invoice_id] }) }
    end
  end

  def delete
    @invoice = Invoice.find(params[:invoice_id])
    @invoice_item = InvoiceItem.find(params[:id])
  end

  def destroy
    @invoice_item = InvoiceItem.find(params[:id])
    invoice = Invoice.find(params[:invoice_id])
    invoice.total_price = invoice.total_price - (@invoice_item.quantity * @invoice_item.price)
    invoice.bal_due = invoice.total_price
    @invoice_item = InvoiceItem.destroy(@invoice_item, invoice)
    @total_price = number_to_currency(Invoice.where(id: params[:invoice_id]).pluck(:total_price)[0])
    flash[:success] = I18n.t('delete_success') if @invoice_item .errors.size == 0

  end

  private
  def invoice_item_params
    params.require(:invoice_item).permit(
        :invoice_id,
        :item_name,
        :quantity,
        :price
    )
  end


end

app/controllers/myc/students_controller.rb
class Myc::StudentsController < ApplicationController
  def index
  end

  def index_data
    respond_to do |format|
      format.html
      format.json { render json: StudentDatatable.new(view_context, { studio_id: session[:current_studio_id] }) }
    end
  end

  def new
    @student = Student.new
    @student.build_family
  end

  def create
    @student = Student.new(student_params.merge(:studio_id => session[:current_studio_id]))
    if @student.save
      flash[:success] = t('save_success')
      redirect_to(:action => 'index')
    else
      flash[:error] = t('save_fail')
      render('new')
    end
  end

  def edit
    @student = Student.find(params[:id])
    @student[:enquiry_date] = @student.enquiry_date.to_s
    @student[:registration_date] = @student.registration_date.to_s
  end

  def update
    puts session[:referrer]
    @student = Student.find(params[:id])

    if @student.update_attributes(student_params)
      flash[:success] = t('save_success')
      redirect_to(:action => 'index')
    else
      flash[:error] = t('save_fail')
      render('edit')
    end
  end

  private
  def student_params
     student_params = params.require(:student).permit(
      :myc_level_id,
      :family_id,
      :enrolment_piano,
      :enrolment_theory,
      :enrolment_other,
      :preferred_day_one,
      :preferred_day_two,
      :preferred_day_three,
      :preferred_time_one,
      :preferred_time_two,
      :preferred_time_three,
      :nric_name,
      :first_name,
      :sur_name,
      :gender,
      :date_of_birth,
      :piano_standard,
      :piano_college,
      :piano_school_attended,
      :theory_standard,
      :theory_college,
      :theory_school_attended,
      :violin_standard,
      :violin_college,
      :violin_school_attended,
      :other_standard,
      :other_college,
      :other_school_attended,
      :instrument_owned_has_piano,
      :instrument_owned_has_organ,
      :instrument_owned_has_keyboard,
      :instrument_owned_has_violin,
      :instrument_owned_other,
      :referred_by,
      :enquiry_date,
      :registration_date,
      :status
    )
     student_params[:enquiry_date] = to_date(student_params[:enquiry_date])
     student_params[:registration_date] = to_date(student_params[:registration_date])

    return student_params

  end

end

app/controllers/myc/teacher_commission_item_additionals_controller.rb
class Myc::TeacherCommissionItemAdditionalsController < ApplicationController
  include ApplicationHelper

  def index_data
    respond_to do |format|
      format.json { render json: TeacherCommissionItemAdditionalDatatable.new(view_context, {teacher_commission_id: params[:teacher_commission_id]}) }
    end
  end

  def new
    @teacher_commission_id = params[:teacher_commission_id]
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.new
  end

  def create
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.validate_lesson_fee_and_no_of_lesson_and_percentage(teacher_commission_item_params)
    if @teacher_commission_item_additional.errors.size == 0
      @teacher_commission_item_additional = TeacherCommissionItemAdditional.new(
          teacher_commission_item_params.merge(teacher_commission_id: params[:teacher_commission_id])
      )
      if @teacher_commission_item_additional.save
        @net_pay = number_to_currency(TeacherCommission.net_pay(params[:teacher_commission_id]))
        flash[:success] = t('save_success')
      end
    end
  end

  def edit
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.find(params[:id])
  end

  def update
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.validate_lesson_fee_and_no_of_lesson_and_percentage(teacher_commission_item_params)
    if @teacher_commission_item_additional.errors.size == 0
      @teacher_commission_item_additional = TeacherCommissionItemAdditional.find(params[:id])
      if @teacher_commission_item_additional.update(teacher_commission_item_params)
        teacher_commission_id = TeacherCommissionItemAdditional.where(id: params[:id]).pluck(:teacher_commission_id).first
        @net_pay = number_to_currency(TeacherCommission.net_pay(teacher_commission_id))
        flash[:success] = t('save_success')
      end
    end
  end

  def delete
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.find(params[:id])
  end

  def destroy
    teacher_commission_id = TeacherCommissionItemAdditional.where(id: params[:id]).pluck(:teacher_commission_id).first
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.find(params[:id])
    @teacher_commission_item_additional.destroy
    if @teacher_commission_item_additional.destroyed?
      @net_pay = number_to_currency(TeacherCommission.net_pay(teacher_commission_id))
      flash[:success] = t('delete_success')
    end
  end

  private
  def teacher_commission_item_params
    params.require(:teacher_commission_item_additional).permit(
        :program,
        :day,
        :time,
        :student_nric_name,
        :lesson_date,
        :term_fee,
        :lesson_fee,
        :no_of_lesson,
        :percentage,
        :commission,
        :remarks
    )
  end
end

app/controllers/myc/teachers_controller.rb
class Myc::TeachersController < ApplicationController
  layout "application"

  def index
  end

  def index_data
    respond_to do |format|
      format.json { render json: MycTeacherDatatable.new(view_context, {studio_id: session[:current_studio_id]}) }
    end
  end

end

app/helpers/myc/myc_classes_helper.rb
module Myc::MycClassesHelper
end

app/helpers/myc/teacher_commission_item_additionals_helper.rb
module Myc::TeacherCommissionItemAdditionalsHelper
end

app/helpers/myc/teachers_helper.rb
module Myc::TeachersHelper
end

app/helpers/myc/users_helper.rb
module Myc::UsersHelper
end

app/views/myc/lessons/_choose_students_to_mark_attendance.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title">Attendance</h4>
</div>
<%= form_tag(mark_attendance_myc_lesson_path, method: "post", id: 'mark_attendance_form') do %>
<div class="modal-body">
  <div id="error-div"></div>

  <div class="row">
    <div class="col-md-12">
      <form id="attendanceForm">
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <% Attendance.statuses.each do |status| %>
                  <% if status[1] == Attendance.statuses[:present] %>
                      <a class="btn btn-outline btn-primary" href="javascript:setAttendance('<%= status[0].humanize %>')"><%= status[0].humanize %></a>
                  <% elsif status[1] != Attendance.statuses[:null] %>
                      <a class="btn btn-outline btn-default" href="javascript:setAttendance('<%= status[0].humanize %>')"><%= status[0].humanize %></a>
                  <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </form>

      <table id="students-attendance-table"  data-source="<%= student_attendance_data_myc_myc_classes_path(lesson_id: @lesson.id, format: :json) %>"  class="table table-bordered table-striped">
        <thead>
        <tr>
          <th><input type="checkbox" id="check-all" ></th>
          <th>Student</th>
          <th>Attendance Status</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>

    </div>
  </div>

  <%= hidden_field_tag(:lesson_id, @lesson.id) %>
  <%= hidden_field_tag(:attendances_data, '') %>
<% end %>
</div>

<div class="modal-footer">
  <%= link_to 'Cancel', '#', class: 'btn btn-default', data: {dismiss: 'modal'} %>
  <button type="button" class="btn btn-success" onclick="markAttendance()">Save</button>
</div>

app/views/myc/lessons/_choose_teacher_to_change.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title">Change Teacher</h4>
</div>

<%= form_tag(change_teacher_myc_lesson_path, method: "post") do %>
<div class="modal-body">

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= label_tag(:teacher_id, "Teacher") %>
        <%= select_tag(:teacher_id, options_for_select(Teacher.teacher_id_and_name_by_studio(session[:current_studio_id]).collect.map {|t| [t.nric_name, t.id ] }), {class: 'form-control', required: "required" }) %>
        <br>
        <%= label_tag('', "Change") %>
        <div>
          <%= radio_button_tag(:change, "OneLesson", true, { id: 'one_lesson'}) %>
          <%= label_tag(:change, "One Lesson") %>
        </div>
        <div>
          <%= radio_button_tag(:change, "ManyLesson", false, { id: 'many_lessons'}) %>
          <%= label_tag(:change, "This and Following lessons") %>
        </div>
      </div>
    </div>


  </div>

</div>

<div class="modal-footer">
  <%= link_to 'Close', '#', class: 'btn btn-default', data: {dismiss: 'modal'} %>
  <%= submit_tag 'Save', class: 'btn btn-success' %>
</div>

<% end %>

app/views/myc/lessons/_set_data_for_lesson_make_up.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title">Lesson Make Up</h4>
</div>

<%= form_tag(lesson_make_up_myc_lesson_path, method: "post", id: 'lessonMakeUpForm') do %>
<div class="modal-body">

    <div class="row" id="makeUpDateTimeRow">
      <div class="col-sm-12">
        <div class="form-group">
          <%= label_tag :make_up_date, "Make Up Date" %>
          <%= text_field_tag :make_up_date, nil, { class: "form-control datePicker", required: "required" } %>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <%= label_tag :make_up_time, "Make Up Time" %>
          <%= text_field_tag :make_up_time, nil, { class: "form-control timePicker", required: "required" } %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <%= label_tag :reason, "Reason" %>
          <%= text_field_tag :reason, nil, { class: "form-control", required: "required" } %>
        </div>
      </div>
    </div>

    <%= hidden_field_tag(:make_up_type, @make_up_type) %>
    <%= hidden_field_tag(:lesson_id, @lesson.id) %>
</div>


<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <%= submit_tag 'Save', class: 'btn btn-success' %>
</div>
<% end %>

app/views/myc/lessons/_unmark_attendance_confirm.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="exampleModalLabel">Confirmation</h4>
</div>
<div class="modal-body">
  <div id="error-div"></div>
  <%= t('confirm_unmark_attendance') %>
</div>
<div class="modal-footer">
  <%= link_to 'No', '#', class: 'btn btn-default', data: {dismiss: 'modal'} %>
  <%= link_to 'Yes', "/myc/lessons/#{@lesson.id}/unmark_attendance", method: :patch, class: 'btn btn-success' %>
</div>

app/views/myc/lessons/choose_students_to_mark_attendance.js.erb
$('.unobtrusive-flash-container').empty() // remove previous message if exists

tableId = 'students-attendance-table';
selectAllCheckboxId = 'check-all';

$("#modal-content").html("<%= j render 'choose_students_to_mark_attendance' %>");
$("#modal").modal("show");


$(document).ready(function() {
  initCheckboxTableWithEnableFeatures(tableId, selectAllCheckboxId, false);
});

function isAttendanceMarkedForAllStudents(selectedRows){
  var result = true;
  selectedRows.every(function () {
    var data = this.data();
    if (data[2] == 'Null') {
      result = false;
    }
  });

  return result;
}

function markAttendance()
{
  $('#error-div').html('');
  var studentAttendanceTable = $('#' + tableId).DataTable();
  var selectedRows = studentAttendanceTable.rows();

  if (!isAttendanceMarkedForAllStudents(selectedRows))
  {
    $('#error-div').html('<%= t('mark_attendance_for_all_students') %>');
    $("#attendance_status option[value='']").prop('selected', true);
  }
  else
  {
    $("#mark_attendance_form").submit();
  }
}

function setAttendance(attendanceStatus){
  var studentAttendanceTable = $('#' + tableId).DataTable();
  var selectedRows = studentAttendanceTable.rows('.active');

  if (selectedRows.data().length == 0)
  {
    $('#error-div').html('<%= t('choose_students') %>');
  }
  else
  {
    var attendancesData = [];
    selectedRows.every( function () {
      var data = this.data();
      attendancesData.push({
        id: data[0], status: attendanceStatus
      });
      data[2] = attendanceStatus; // update data source for the row
      $('#' + tableId + ' tbody input[type="checkbox"]:checked').trigger('click');    //unselect all selected checkboxes
      this.invalidate(); // invalidate the data DataTables has cached for this row
    });

    $('#attendances_data').val(JSON.stringify(attendancesData));
  }
}

app/views/myc/lessons/choose_teacher_to_change.js.erb
$('.unobtrusive-flash-container').empty() // remove previous message if exists
<% if @lesson.errors.any? %>
  UnobtrusiveFlash.showFlashMessage('<%= @lesson.errors.full_messages[0] %>', {type: 'error', timeout: 0});
<% else %>
  $("#modal-content").html("<%= j render 'choose_teacher_to_change' %>")
  $("#modal").modal("show")
<% end %>

$('#operation-menu').dropdown("toggle");

$(document).ready(function() {
  $("#modal").on('shown.bs.modal', function () {
    var validator = $("#change_teacher_form").validate(setHighlight());
    validator.element("#teacher_id");
  });
})

app/views/myc/lessons/set_data_for_lesson_make_up.js.erb
$('.unobtrusive-flash-container').empty() // remove previous message if exists
<% if @lesson.errors.any? %>
UnobtrusiveFlash.showFlashMessage('<%= @lesson.errors.full_messages[0] %>', {type: 'error', timeout: 0});
<% else %>
$("#modal-content").html("<%= j render 'set_data_for_lesson_make_up' %>")
$("#modal").modal("show")
<% end %>

function setDefaultForControls(){
  $('#makeUpDateTimeRow').show();
  $('#make_up_date').val(null);
  $('#make_up_time').val(null);
  $('#reason').val(null);

  validateControls();
}

function validateControls(){
  var validator = $("#lessonMakeUpForm").validate(setHighlight());
  validator.element("#make_up_date");
  validator.element('#make_up_time');
  validator.element('#reason');
}

function showOrHideControlsByMakeUpType(makeUpType){
  if (makeUpType == 'makeUpToSpecificDate')
  {
    $("#makeUpDateTimeRow").show();
  }
  else if (makeUpType == 'afterLastLesson')
  {
    $("#makeUpDateTimeRow").hide();
  }

  validateControls();
}

$(document).ready(function() {
  setDefaultForControls();
  showOrHideControlsByMakeUpType('<%= @make_up_type %>')
  $(function () {
    $('.datePicker').datetimepicker({
      format: 'DD/MM/YY',
      showTodayButton: true
    });
  });

  $(function () {
    $('.timePicker').datetimepicker({
      format: 'LT'
    });
  });

  $("#modal").on('shown.bs.modal', function () {
    validateControls();
  });
});

app/views/myc/lessons/unmark_attendance_confirm.js.erb
$("#modal-content").html("<%= j render 'unmark_attendance_confirm' %>")
$("#modal").modal("show")