config/routes.rb
Rails.application.routes.draw do

  get '/' => 'home#index' # this is only used for devise > after change password > redirect

  # get 'logout/index'
  resources :logout, only: [:index]

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration' # change password without registration
    patch 'users' => 'devise/registrations#update', as: 'user_registration' # change password without registration
  end

  resources :home, only: [:index, :show]

  namespace :hq do
    resources :myc_programs, only: [:index, :index_data] do
      collection do
        post 'index_data'
      end
    end

    resources :users do
      collection do
        post 'index_data'
      end
      member do
        get 'invite_confirm'
        patch 'invite'
        get 'edit_status'
        get 'set_profile' # after login
      end

      resources :teachers, only: [:new, :create, :edit, :update]
      resources :studio_users, only: [:index, :new, :create] do
        collection do
          post 'index_data'
        end
      end
    end

    resources :teachers, only: [:edit, :update]

    resources :studio_users, only: [:destroy] do
      member do
        get 'delete'
      end
    end

    resources :studios do
      collection do
        post 'data'
      end
    end

    resources :product_codes, except: [:delete, :show] do
      collection do
        post 'index_data'
      end
      member do
        post 'pack_data_by_code'
        get 'select_pack'
        post 'add_pack'
        get 'remove_pack_confirm/:product_pack_id', action: 'remove_pack_confirm'
        delete 'remove_pack/:product_pack_id', action: 'remove_pack'

        post 'item_data_by_code'
        get 'select_item'
        post 'add_item'
        get 'remove_item_confirm/:product_item_id', action: 'remove_item_confirm'
        delete 'remove_item/:product_item_id', action: 'remove_item'
        get 'show_pack_items/:product_pack_id', action: 'show_pack_items'
      end
    end

    resources :product_packs, except: [:delete, :show] do
      collection do
        post 'index_data'
      end
      member do
        post 'item_data_by_pack'
        get 'select_item'
        post 'add_item'
        get 'remove_item_confirm/:product_item_id', action: 'remove_item_confirm'
        delete 'remove_item/:product_item_id', action: 'remove_item'
      end

      resources :product_items, only: [:index]
    end

    resources :product_items, only: [:index, :new, :create, :edit, :update] do
      collection do
        post 'index_data'
      end
    end

    resources :student_reports, only: [:index] do
      collection do
        post 'index_data'
        post 'index_total_data'
        post 'generate'
      end
    end
  end

  namespace :myc do
    resources :calendar, only: [:index]

    resources :teachers, only: [:index] do
      collection do
        post 'index_data'
      end
    end

    resources :students, except: [:delete, :show] do
      collection do
        post 'index_data'
      end
    end

    resources :myc_classes, only: [:index, :new, :create, :show] do
      collection do
        post 'index_data'
        post 'new_students_data'
        post 'old_students_data'
        post 'in_class_students_data'
        post 'student_attendance_data'
      end

      member do
        get 'choose_students_to_add'
        post 'add_students'

        get 'choose_student_to_remove'
        post 'check_student_attendance'
        post 'remove_student'

        get 'dissolve_confirm'
        patch 'dissolve'

        get 'undo_dissolve_confirm'
        patch 'undo_dissolve'
      end
    end

    resources :lessons do
      member do
        get 'choose_teacher_to_change'
        post 'change_teacher'

        get 'set_data_for_lesson_make_up/:make_up_type', action: 'set_data_for_lesson_make_up'
        post 'lesson_make_up'

        get 'choose_students_to_mark_attendance'
        post 'mark_attendance'

        get 'unmark_attendance_confirm'
        patch 'unmark_attendance'
      end
    end

    resources :families, except: [:delete] do
      collection do
        post 'index_data'
      end
    end

    resources :holidays, except: [:delete]  do
      collection do
        post 'index_data'
      end
    end

    resources :invoices, except: [:delete]  do
      resources :invoice_items, only: [:destroy] do
        collection do
          post 'index_data'
        end
        member do
          get 'delete', action: 'delete'
        end
      end

      collection do
        post 'index_data'
        post 'invoice_new_student_data'
        post 'invoice_existing_student_data'

        get 'choose_student', action: 'choose_student'
        post 'add_new_student', action: 'add_new_student'
        post 'add_existing_student', action: 'add_existing_student'

        get 'fee_item/program', action: 'program'
        get 'fee_item/discount', action: 'discount'
        get 'fee_item/lesson', action: 'lesson'
        post 'material_data', action: 'material_data'

      end
      member do
        get 'fee_item/program', action: 'program'
        get 'fee_item/discount', action: 'discount'
        get 'fee_item/lesson', action: 'lesson'
        get 'fee_item/material', action: 'material'
        get 'fee_item/other', action: 'other'

        post 'program_fee_item_data', action: 'program_fee_item_data'
        post 'discount_fee_item_data', action: 'discount_fee_item_data'
        post 'lesson_fee_item_data', action: 'lesson_fee_item_data'
        post 'add_program_fee_item', action: 'add_program_fee_item'
        post 'add_discount_fee_item', action: 'add_discount_fee_item'
        post 'add_lesson_fee_item', action: 'add_lesson_fee_item'
        post 'add_material_fee_item', action: 'add_material_fee_item'
        post 'add_other_fee_item', action: 'add_other_fee_item'
      end
    end

    resources :teacher_commissions, only: [:index, :show, :edit, :update] do
      collection do
        post 'index_data'
        post 'show_data'
        get 'generate_confirm'
        post 'generate'
      end
      resources :teacher_commission_items do
        collection do
          post 'index_data'
        end
        member do
          patch 'update_percentage'
          get 'edit_percentage'
          get 'edit_remarks'
        end
      end

      resources :teacher_commission_item_additionals, only: [:new, :create] do
        collection do
          post 'index_data'
        end
      end

      resources :teacher_commission_others, only: [:new, :create] do
        collection do
          post 'index_data'
        end
      end
    end

    resources :teacher_commission_item_additionals, only: [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :teacher_commission_others, only: [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end
  end


end

app/controllers/myc/calendar_controller.rb
class Myc::CalendarController < ApplicationController
  layout 'application'

  def index
    start_date = params['start']
    end_date = params['end']
    @holidays = Holiday.events_for_calendar(session[:current_studio_id], start_date, end_date)
    @lessons = Lesson.events_for_calendar(session[:current_studio_id], start_date, end_date)
  end
end

app/controllers/myc/families_controller.rb
class Myc::FamiliesController < ApplicationController
  def index_data
    respond_to do |format|
      format.html
      format.json { render json: FamilyDatatable.new(view_context, { studio_id: session[:current_studio_id] }) }
    end
  end

  def new
    session[:referrer] = request.referrer # set the previous url
    @family = Family.new
  end

  def create
    @family = Family.new(family_params.merge(:studio_id => session[:current_studio_id]))
    if @family.save
      flash[:success] = t('save_success')
      if session[:referrer] == nil
        redirect_to(action: 'index')
      else
        redirect_to(session[:referrer])
      end
      session.delete(:referrer)
    else
      flash[:error] = t('save_fail')
      render('new')
    end
  end

  def edit
    session[:referrer] = request.referrer
    @family = Family.find(params[:id])
  end

  def update
    @family = Family.find(params[:id])
    if @family.update_attributes(family_params)
      flash[:success] = t('save_success')
      if session[:referrer] == nil
        redirect_to(action: 'index')
      else
        redirect_to(session[:referrer])
      end
      session.delete(:referrer)
    else
      render('edit')
    end
  end

  def show
      @family = Family.find(params[:family_id])
      respond_to do |format|
      format.json { render :json => {:data => @family}, status: :ok }
      end
  end

  private
  def family_params
    params.require(:family).permit(
        :address1,
        :address2,
        :postal_code,
        :city_or_state,
        :country,
        :primary_contact_name,
        :primary_contact_relationship,
        :primary_contact_phone_no,
        :primary_contact_email,
        :primary_contact_occupation,
        :primary_contact_music_background,
        :primary_contact_accompany_for_student,
        :other_contact_name,
        :other_contact_relationship,
        :other_contact_phone_no,
        :other_contact_email,
        :other_contact_occupation,
        :other_contact_music_background,
        :other_contact_accompany_for_student,
        :status
    )
  end
end

app/controllers/myc/holidays_controller.rb
class Myc::HolidaysController < ApplicationController
  def index_data
    respond_to do |format|
      format.html
      format.json { render json: HolidayDatatable.new(view_context, { studio_id: session[:current_studio_id] }) }
    end
  end

  def index
  end

  def new
    @holiday = Holiday.new
  end

  def create
    @holiday = Holiday.new(holiday_params.merge(:studio_id => session[:current_studio_id]))
    if @holiday.save
      flash[:success] = t('save_success')
      redirect_to(:action => 'index')
    else
      flash[:error] = t('save_fail')
      render('new')
    end
  end

  def edit
    session[:referrer] = request.referrer
    @holiday = Holiday.find(params[:id])
    @holiday[:holiday_date] = @holiday.holiday_date.to_s
  end

  def update
    @holiday = Holiday.find(params[:id])
    if @holiday.update_attributes(holiday_params)
      flash[:success] = t('save_success')
      redirect_to(:action => 'index')
    else
      render('edit')
    end
  end

  private
  def holiday_params
    holiday_params = params.require(:holiday).permit(
        :holiday_date,
        :holiday_name,
    )
    holiday_params[:holiday_date] = to_date(holiday_params[:holiday_date])
    return holiday_params
  end
end

app/controllers/myc/invoice_items_controller.rb
class Myc::InvoiceItemsController < ApplicationController
  include ApplicationHelper
  def index_data
    respond_to do |format|
      format.html
      format.json { render json: InvoiceItemDatatable.new(view_context, { invoice_id: params[:invoice_id] }) }
    end
  end

  def delete
    @invoice = Invoice.find(params[:invoice_id])
    @invoice_item = InvoiceItem.find(params[:id])
  end

  def destroy
    @invoice_item = InvoiceItem.find(params[:id])
    invoice = Invoice.find(params[:invoice_id])
    invoice.total_price = invoice.total_price - (@invoice_item.quantity * @invoice_item.price)
    invoice.bal_due = invoice.total_price
    @invoice_item = InvoiceItem.destroy(@invoice_item, invoice)
    @total_price = number_to_currency(Invoice.where(id: params[:invoice_id]).pluck(:total_price)[0])
    flash[:success] = I18n.t('delete_success') if @invoice_item .errors.size == 0

  end

  private
  def invoice_item_params
    params.require(:invoice_item).permit(
        :invoice_id,
        :item_name,
        :quantity,
        :price
    )
  end


end

app/controllers/myc/students_controller.rb
class Myc::StudentsController < ApplicationController
  def index
  end

  def index_data
    respond_to do |format|
      format.html
      format.json { render json: StudentDatatable.new(view_context, { studio_id: session[:current_studio_id] }) }
    end
  end

  def new
    @student = Student.new
    @student.build_family
  end

  def create
    @student = Student.new(student_params.merge(:studio_id => session[:current_studio_id]))
    if @student.save
      flash[:success] = t('save_success')
      redirect_to(:action => 'index')
    else
      flash[:error] = t('save_fail')
      render('new')
    end
  end

  def edit
    @student = Student.find(params[:id])
    @student[:enquiry_date] = @student.enquiry_date.to_s
    @student[:registration_date] = @student.registration_date.to_s
  end

  def update
    puts session[:referrer]
    @student = Student.find(params[:id])

    if @student.update_attributes(student_params)
      flash[:success] = t('save_success')
      redirect_to(:action => 'index')
    else
      flash[:error] = t('save_fail')
      render('edit')
    end
  end

  private
  def student_params
     student_params = params.require(:student).permit(
      :myc_level_id,
      :family_id,
      :enrolment_piano,
      :enrolment_theory,
      :enrolment_other,
      :preferred_day_one,
      :preferred_day_two,
      :preferred_day_three,
      :preferred_time_one,
      :preferred_time_two,
      :preferred_time_three,
      :nric_name,
      :first_name,
      :sur_name,
      :gender,
      :date_of_birth,
      :piano_standard,
      :piano_college,
      :piano_school_attended,
      :theory_standard,
      :theory_college,
      :theory_school_attended,
      :violin_standard,
      :violin_college,
      :violin_school_attended,
      :other_standard,
      :other_college,
      :other_school_attended,
      :instrument_owned_has_piano,
      :instrument_owned_has_organ,
      :instrument_owned_has_keyboard,
      :instrument_owned_has_violin,
      :instrument_owned_other,
      :referred_by,
      :enquiry_date,
      :registration_date,
      :status
    )
     student_params[:enquiry_date] = to_date(student_params[:enquiry_date])
     student_params[:registration_date] = to_date(student_params[:registration_date])

    return student_params

  end

end

app/controllers/myc/teacher_commission_item_additionals_controller.rb
class Myc::TeacherCommissionItemAdditionalsController < ApplicationController
  include ApplicationHelper

  def index_data
    respond_to do |format|
      format.json { render json: TeacherCommissionItemAdditionalDatatable.new(view_context, {teacher_commission_id: params[:teacher_commission_id]}) }
    end
  end

  def new
    @teacher_commission_id = params[:teacher_commission_id]
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.new
  end

  def create
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.validate_lesson_fee_and_no_of_lesson_and_percentage(teacher_commission_item_params)
    if @teacher_commission_item_additional.errors.size == 0
      @teacher_commission_item_additional = TeacherCommissionItemAdditional.new(
          teacher_commission_item_params.merge(teacher_commission_id: params[:teacher_commission_id])
      )
      if @teacher_commission_item_additional.save
        @net_pay = number_to_currency(TeacherCommission.net_pay(params[:teacher_commission_id]))
        flash[:success] = t('save_success')
      end
    end
  end

  def edit
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.find(params[:id])
  end

  def update
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.validate_lesson_fee_and_no_of_lesson_and_percentage(teacher_commission_item_params)
    if @teacher_commission_item_additional.errors.size == 0
      @teacher_commission_item_additional = TeacherCommissionItemAdditional.find(params[:id])
      if @teacher_commission_item_additional.update(teacher_commission_item_params)
        teacher_commission_id = TeacherCommissionItemAdditional.where(id: params[:id]).pluck(:teacher_commission_id).first
        @net_pay = number_to_currency(TeacherCommission.net_pay(teacher_commission_id))
        flash[:success] = t('save_success')
      end
    end
  end

  def delete
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.find(params[:id])
  end

  def destroy
    teacher_commission_id = TeacherCommissionItemAdditional.where(id: params[:id]).pluck(:teacher_commission_id).first
    @teacher_commission_item_additional = TeacherCommissionItemAdditional.find(params[:id])
    @teacher_commission_item_additional.destroy
    if @teacher_commission_item_additional.destroyed?
      @net_pay = number_to_currency(TeacherCommission.net_pay(teacher_commission_id))
      flash[:success] = t('delete_success')
    end
  end

  private
  def teacher_commission_item_params
    params.require(:teacher_commission_item_additional).permit(
        :program,
        :day,
        :time,
        :student_nric_name,
        :lesson_date,
        :term_fee,
        :lesson_fee,
        :no_of_lesson,
        :percentage,
        :commission,
        :remarks
    )
  end
end

app/controllers/myc/teachers_controller.rb
class Myc::TeachersController < ApplicationController
  layout "application"

  def index
  end

  def index_data
    respond_to do |format|
      format.json { render json: MycTeacherDatatable.new(view_context, {studio_id: session[:current_studio_id]}) }
    end
  end

end

app/helpers/myc/myc_classes_helper.rb
module Myc::MycClassesHelper
end

app/helpers/myc/teacher_commission_item_additionals_helper.rb
module Myc::TeacherCommissionItemAdditionalsHelper
end

app/helpers/myc/teachers_helper.rb
module Myc::TeachersHelper
end

app/helpers/myc/users_helper.rb
module Myc::UsersHelper
end

app/views/myc/myc_classes/_choose_students_to_add.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title">Add Student</h4>
</div>

<%= form_tag(add_students_myc_myc_class_path, method: "post") do %>
<div class="modal-body">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#newStudentsTab">New Students</a></li>
    <li><a data-toggle="tab" href="#oldStudentsTab">Existing Students</a></li>
  </ul>

  <div class="tab-content">

    <div id="newStudentsTab" class="tab-pane fade in active">
      <table id="new-students-table" data-source="<%= new_students_data_myc_myc_classes_path(myc_class_id: @myc_class.id, format: :json) %>" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th><input type="checkbox" id="check-all" ></th>
          <th>Student Name</th>
          <th>Interested Program Name</th>
          <th>Student Status</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>

    <div id="oldStudentsTab" class="tab-pane fade">
      <table id="old-students-table" data-source="<%= old_students_data_myc_myc_classes_path(myc_class_id: @myc_class.id, format: :json) %>" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th><input type="checkbox" id="check-all" ></th>
          <th>Student Name</th>
          <th>Latest Class</th>
          <th>Student Status</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>

  </div>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <%= submit_tag 'Save', class: 'btn btn-success' %>
</div>
<% end %>

app/views/myc/myc_classes/_dissolve_confirm.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="exampleModalLabel">Confirmation</h4>
</div>
<div class="modal-body">
  <div id="error-div"></div>
  <%= t('confirm_dissolve') %>
</div>
<div class="modal-footer">
  <%= link_to 'No', '#', class: 'btn btn-default', data: {dismiss: 'modal'} %>
  <%= link_to 'Yes', "/myc/myc_classes/#{@myc_class.id}/dissolve", method: :patch, class: 'btn btn-success' %>
</div>

app/views/myc/myc_classes/_form.html.erb
<%= javascript_tag do %>



    $(document).ready(function() {
        var validator = $("#form_id").validate(setHighlight());
        validator.element('#myc_class_start_date');
        validator.element('#myc_class_start_time');
        validator.element('#myc_class_myc_level_id');
        validator.element('#myc_class_teacher_id');


        $(function () {
            $('.datePicker').datetimepicker({
                format: 'DD/MM/YY',
                showTodayButton: true
            });
        });

      $(function () {
          $('.timePicker').datetimepicker({
              format: 'LT'
          });
      });
    });

<% end %>

<%= error_messages_for(@myc_class) %>

<div style="float: right; padding-top: 20px">
  <%= link_to "Cancel", {:action => :index}, :class => "btn btn-default" %>
  <%= f.submit 'Save', :class => 'btn btn-success' %>
</div>

<div class="clearfix"></div>

<hr/>

<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :start_date, "Start Date" %>
      <%= f.text_field :start_date, class: "form-control datePicker", required: "required" %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label(:myc_level_id, "Program") %>
      <%= f.select(:myc_level_id, options_for_select(MycProgram.active_program_and_level_order_by_display_order.collect.map {|p| [p.program_and_level_name, p.id ] }), {}, {class: 'form-control', required: "required" }) %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :start_time, "Start Time" %>
      <%= f.text_field :start_time, class: "form-control timePicker", required: "required" %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label(:teacher_id, "Teacher") %>
      <%= f.select(:teacher_id, options_for_select(Teacher.teacher_id_and_name_by_studio(session[:current_studio_id]).collect.map {|t| [t.nric_name, t.id ] }), {}, {class: 'form-control', required: "required" }) %>
    </div>
  </div>
</div>

app/views/myc/myc_classes/_remove_student_confirm.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="exampleModalLabel">Confirmation</h4>
</div>
<%= form_tag(remove_student_myc_myc_class_path, method: "post") do %>
<div class="modal-body">
  <div id="error-div"></div>
  <%= t('confirm_remove_student') %>
  <%= hidden_field_tag(:student_id, @student_id) %>
  <%= hidden_field_tag(:class_student_status, '') %>
</div>
<div class="modal-footer">
  <%= link_to 'No', '#', class: 'btn btn-default', data: {dismiss: 'modal'} %>
  <%= submit_tag 'Yes', class: 'btn btn-success' %>
</div>
<% end %>

app/views/myc/myc_classes/_terminate_student.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title">Remove Student</h4>
</div>

<div class="modal-body">

    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= label_tag(:student_status, "Reason") %>
          <%= select_tag :student_status, options_for_select(MycClassStudent.status_for_remove_student_from_class.map { |s| [s[0].humanize, s[0]] }), class: "form-control" %>
        </div>
      </div>
    </div>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <button type="button" class="btn btn-success" onclick="terminateStudent()">Remove</button>
</div>


<script>
  function terminateStudent()
  {
    var status = $('#student_status').val();
    $("#modal-content").html("<%= j render 'remove_student_confirm' %>");
    $('#class_student_status').val(status);
    $("#modal").modal("show");
  }
</script>

app/views/myc/myc_classes/_undo_dissolve_confirm.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="exampleModalLabel">Confirmation</h4>
</div>
<div class="modal-body">
  <div id="error-div"></div>
  <%= t('confirm_undo_dissolve') %>
</div>
<div class="modal-footer">
  <%= link_to 'No', '#', class: 'btn btn-default', data: {dismiss: 'modal'} %>
  <%= link_to 'Yes', "/myc/myc_classes/#{@myc_class.id}/undo_dissolve", method: :patch, class: 'btn btn-success' %>
</div>

app/views/myc/myc_classes/check_student_attendance.js.erb
$('.unobtrusive-flash-container').empty() // remove previous message if exists

<% if @marked_attendance %>
  $("#modal-content").html("<%= j render 'terminate_student' %>");
<% else %>
  $("#modal-content").html("<%= j render 'remove_student_confirm' %>");
<% end %>

$("#modal").modal("show");

app/views/myc/myc_classes/dissolve_confirm.js.erb
$('.unobtrusive-flash-container').empty() // remove previous message if exists

<% if MycClass.statuses[@myc_class.status] != MycClass.statuses[:on_going] %>
  UnobtrusiveFlash.showFlashMessage('<%= t('cant_dissolve_class_because_status_is_not_on_going') %>', {type: 'error', timeout: 0});
<% else %>
  $("#modal-content").html("<%= j render 'dissolve_confirm' %>");
  $("#modal").modal("show");
<% end %>

app/views/myc/myc_classes/index.html.erb
<script>

    var tableId = 'classes-table';

    $(document).ready(function() {
      $('#teacher-select').val('');
      $('#level-select').val('');
      $('#student-select').val('');
      $('#status-select').val('<%= MycClass.statuses[:on_going] %>');
        filterData();
    });

    function filterData()
    {
      var data = {
          teacher_id: $('#teacher-select').val(),
          myc_level_id: $('#level-select').val(),
          student_id: $('#student-select').val(),
          status: $('#status-select').val()
        };
      $('#' + tableId).DataTable().destroy();
      var dataTable = initTableWithDeferLoadingAndParameters(tableId, true, 1, 'asc', data);

      dataTable.draw();
    }

</script>

<% @breadcrumb = "Classes" %>

<div style="float: left; padding-top: 20px">
  <a href="#filter" class="btn btn-default" data-toggle="collapse">Filter</a>
</div>

<div style="float: right; padding-top: 20px">
  <%= link_to "New", {:action => :new},  :class => "btn btn-w-m btn-success" %>
</div>

<div class="clearfix"></div>

<div id="filter" class="collapse">
  <div class="row">

    <div class="col-sm-6">
      <div class="form-group">
        Teacher
        <select id="teacher-select" class="form-control">
          <option value=""></option>
          <% Teacher.teacher_id_and_name_by_studio(session[:current_studio_id]).each do |teacher| %>
              <option value=<%= teacher.id %>><%= teacher.nric_name %></option>
          <% end %>
        </select>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        Program
        <select id="level-select" class="form-control">
          <option value=""></option>
          <% MycProgram.active_program_and_level_order_by_display_order.each do |myc_level| %>
              <option value=<%= myc_level.id %> ><%= myc_level.program_and_level_name %></option>
          <% end %>
        </select>
      </div>
    </div>

  </div>

  <div class="row">

    <div class="col-sm-6">
      <div class="form-group">
        Student
        <select id="student-select" class="form-control">
          <option value=""></option>
          <% Student.active_student_id_and_name_by_studio(session[:current_studio_id]).each do |student| %>
              <option value=<%= student.id %>><%= student.nric_name %></option>
          <% end %>
        </select>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        Status
        <select id="status-select" class="form-control">
          <option value=""></option>
          <% MycClass.statuses.each do |status| %>
              <option value=<%= status[1] %> <%= 'selected=selected' if status[1] == MycClass.statuses[:on_going] %> ><%= status[0].humanize %></option>
          <% end %>
        </select>
      </div>
    </div>

  </div>

  <button id="btnFilter" class="btn btn-primary inline" onclick="filterData()">Search</button>

</div>

<hr>

<div>
  <table id="classes-table" data-source="<%= index_data_myc_myc_classes_path(format: :json) %>" class="table table-bordered">
    <thead>
      <tr>
        <th>Program</th>
        <th>Day</th>
        <th>Time</th>
        <th>Teacher</th>
        <th>Class Status</th>
        <th>Latest Conducted Lesson No</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/myc/myc_classes/new.html.erb
<% @breadcrumb = link_to('Classes', {:action => 'index'}) + " / " + "<b>New</b>".html_safe %>

<%= form_for @myc_class, url: {:action => 'create'}, :html => {:id => 'form_id'} do |f| %>

    <%= render(:partial => "form", :locals => {:f => f}) %>

<% end %>