config/routes.rb
Rails.application.routes.draw do

  get '/' => 'home#index' # this is only used for devise > after change password > redirect

  # get 'logout/index'
  resources :logout, only: [:index]

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration' # change password without registration
    patch 'users' => 'devise/registrations#update', as: 'user_registration' # change password without registration
  end

  resources :home, only: [:index, :show]

  namespace :hq do
    resources :myc_programs, only: [:index, :index_data] do
      collection do
        post 'index_data'
      end
    end

    resources :users do
      collection do
        post 'index_data'
      end
      member do
        get 'invite_confirm'
        patch 'invite'
        get 'edit_status'
        get 'set_profile' # after login
      end

      resources :teachers, only: [:new, :create, :edit, :update]
      resources :studio_users, only: [:index, :new, :create] do
        collection do
          post 'index_data'
        end
      end
    end

    resources :teachers, only: [:edit, :update]

    resources :studio_users, only: [:destroy] do
      member do
        get 'delete'
      end
    end

    resources :studios do
      collection do
        post 'data'
      end
    end

    resources :product_codes, except: [:delete, :show] do
      collection do
        post 'index_data'
      end
      member do
        post 'pack_data_by_code'
        get 'select_pack'
        post 'add_pack'
        get 'remove_pack_confirm/:product_pack_id', action: 'remove_pack_confirm'
        delete 'remove_pack/:product_pack_id', action: 'remove_pack'

        post 'item_data_by_code'
        get 'select_item'
        post 'add_item'
        get 'remove_item_confirm/:product_item_id', action: 'remove_item_confirm'
        delete 'remove_item/:product_item_id', action: 'remove_item'
        get 'show_pack_items/:product_pack_id', action: 'show_pack_items'
      end
    end

    resources :product_packs, except: [:delete, :show] do
      collection do
        post 'index_data'
      end
      member do
        post 'item_data_by_pack'
        get 'select_item'
        post 'add_item'
        get 'remove_item_confirm/:product_item_id', action: 'remove_item_confirm'
        delete 'remove_item/:product_item_id', action: 'remove_item'
      end

      resources :product_items, only: [:index]
    end

    resources :product_items, only: [:index, :new, :create, :edit, :update] do
      collection do
        post 'index_data'
      end
    end

    resources :student_reports, only: [:index] do
      collection do
        post 'index_data'
        post 'index_total_data'
        post 'generate'
      end
    end
  end

  namespace :myc do
    resources :calendar, only: [:index]

    resources :teachers, only: [:index] do
      collection do
        post 'index_data'
      end
    end

    resources :students, except: [:delete, :show] do
      collection do
        post 'index_data'
      end
    end

    resources :myc_classes, only: [:index, :new, :create, :show] do
      collection do
        post 'index_data'
        post 'new_students_data'
        post 'old_students_data'
        post 'in_class_students_data'
        post 'student_attendance_data'
      end

      member do
        get 'choose_students_to_add'
        post 'add_students'

        get 'choose_student_to_remove'
        post 'check_student_attendance'
        post 'remove_student'

        get 'dissolve_confirm'
        patch 'dissolve'

        get 'undo_dissolve_confirm'
        patch 'undo_dissolve'
      end
    end

    resources :lessons do
      member do
        get 'choose_teacher_to_change'
        post 'change_teacher'

        get 'set_data_for_lesson_make_up/:make_up_type', action: 'set_data_for_lesson_make_up'
        post 'lesson_make_up'

        get 'choose_students_to_mark_attendance'
        post 'mark_attendance'

        get 'unmark_attendance_confirm'
        patch 'unmark_attendance'
      end
    end

    resources :families, except: [:delete] do
      collection do
        post 'index_data'
      end
    end

    resources :holidays, except: [:delete]  do
      collection do
        post 'index_data'
      end
    end

    resources :invoices, except: [:delete]  do
      resources :invoice_items, only: [:destroy] do
        collection do
          post 'index_data'
        end
        member do
          get 'delete', action: 'delete'
        end
      end

      collection do
        post 'index_data'
        post 'invoice_new_student_data'
        post 'invoice_existing_student_data'

        get 'choose_student', action: 'choose_student'
        post 'add_new_student', action: 'add_new_student'
        post 'add_existing_student', action: 'add_existing_student'

        get 'fee_item/program', action: 'program'
        get 'fee_item/discount', action: 'discount'
        get 'fee_item/lesson', action: 'lesson'
        post 'material_data', action: 'material_data'

      end
      member do
        get 'fee_item/program', action: 'program'
        get 'fee_item/discount', action: 'discount'
        get 'fee_item/lesson', action: 'lesson'
        get 'fee_item/material', action: 'material'
        get 'fee_item/other', action: 'other'

        post 'program_fee_item_data', action: 'program_fee_item_data'
        post 'discount_fee_item_data', action: 'discount_fee_item_data'
        post 'lesson_fee_item_data', action: 'lesson_fee_item_data'
        post 'add_program_fee_item', action: 'add_program_fee_item'
        post 'add_discount_fee_item', action: 'add_discount_fee_item'
        post 'add_lesson_fee_item', action: 'add_lesson_fee_item'
        post 'add_material_fee_item', action: 'add_material_fee_item'
        post 'add_other_fee_item', action: 'add_other_fee_item'
      end
    end

    resources :teacher_commissions, only: [:index, :show, :edit, :update] do
      collection do
        post 'index_data'
        post 'show_data'
        get 'generate_confirm'
        post 'generate'
      end
      resources :teacher_commission_items do
        collection do
          post 'index_data'
        end
        member do
          patch 'update_percentage'
          get 'edit_percentage'
          get 'edit_remarks'
        end
      end

      resources :teacher_commission_item_additionals, only: [:new, :create] do
        collection do
          post 'index_data'
        end
      end

      resources :teacher_commission_others, only: [:new, :create] do
        collection do
          post 'index_data'
        end
      end
    end

    resources :teacher_commission_item_additionals, only: [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :teacher_commission_others, only: [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end
  end


end

app/controllers/hq/myc_programs_controller.rb
class Hq::MycProgramsController < ApplicationController

  def index
    authorize User
  end

  def index_data
    respond_to do |format|
      format.json { render json: MycProgramDatatable.new(view_context) }
    end
  end
end

app/controllers/hq/product_codes_controller.rb
class Hq::ProductCodesController < ApplicationController
  include ApplicationHelper

  def index
  end

  def index_data
    respond_to do |format|
      format.json { render json: ProductCodeDatatable.new(view_context) }
    end
  end

  def pack_data_by_code
    respond_to do |format|
      format.json { render json: ProductPackByCodeDatatable.new(view_context, {product_code_id: params[:id]}) }
    end
  end

  def item_data_by_code
    respond_to do |format|
      format.json { render json: ProductItemByCodeDatatable.new(view_context, {product_code_id: params[:id]}) }
    end
  end

  def show_pack_items
    @product_pack_id = params[:product_pack_id]
  end

  def new
    @product_code = ProductCode.new
    @product_code.price = 0.0
    # @product_group_select_options = ProductGroup.select_options_id_description
    @myc_program_select_options = MycProgram.active_myc_programs_order_by_display_order

  end

  def create
    @product_code = ProductCode.new(product_code_params)

    if @product_code.save
      flash[:success] = t('save_success')
      redirect_to "/hq/product_codes/#{@product_code.id}/edit"
    else
      flash[:error] = t('save_fail')
      @myc_program_select_options = MycProgram.active_myc_programs_order_by_display_order
      render 'new'
    end
  end

  def edit
    @product_code = ProductCode.find(params[:id])
    @cost = ProductCode.cost(params[:id])
    @myc_program_select_options = MycProgram.active_myc_programs_order_by_display_order
  end

  def update
    @product_code = ProductCode.find(params[:id])

    if @product_code.update(product_code_params)
      flash[:success] = t('save_success')
      redirect_to action: 'index'
    else
      flash[:error] = t('save_fail')
      @myc_program_select_options = MycProgram.active_myc_programs_order_by_display_order
      render 'edit'
    end
  end

  def select_pack
    @product_code_id = params[:id]
  end

  def add_pack
    if params[:product_pack_id].blank?
      @product_pack = ProductPack.new
      @product_pack.errors[:base] << t('product_pack_cannot_be_empty')
    else
      @product_code = ProductCode.find(params[:id])
      @product_pack = ProductPack.find(params[:product_pack_id])
      if @product_code.product_packs.include?(@product_pack)
        @product_pack.errors[:base] << t('product_pack_already_exists')
      else
        @product_code.product_packs << @product_pack
        @cost = number_to_currency(ProductCode.cost(params[:id]))
        flash[:success] = t('save_success')
      end
    end
  end

  def remove_pack_confirm
    @product_code_id = params[:id]
    @product_pack_id = params[:product_pack_id]
  end

  def remove_pack
    @product_code = ProductCode.find(params[:id])
    @product_pack = ProductPack.find(params[:product_pack_id])
    @product_code.product_packs.delete(@product_pack)
    @cost = number_to_currency(ProductCode.cost(params[:id]))
    flash[:success] = t('save_success') unless @product_code.product_packs.include?(@product_pack)
  end

  def select_item
    @product_code_id = params[:id]
  end

  def add_item
    if params[:product_item_id].blank?
      @product_item = ProductItem.new
      @product_item.errors[:base] << t('product_item_cannot_be_empty')
    else
      @product_code = ProductCode.find(params[:id])
      @product_item = ProductItem.find(params[:product_item_id])
      if @product_code.product_items.include?(@product_item)
        @product_item.errors[:base] << t('product_item_already_exists')
      else
        @product_code.product_items << @product_item
        @cost = number_to_currency(ProductCode.cost(params[:id]))
        flash[:success] = t('save_success')
      end
    end
  end

  def remove_item_confirm
    @product_code_id = params[:id]
    @product_item_id = params[:product_item_id]
  end

  def remove_item
    @product_code = ProductCode.find(params[:id])
    @product_item = ProductItem.find(params[:product_item_id])
    @product_code.product_items.delete(@product_item)
    @cost = number_to_currency(ProductCode.cost(params[:id]))
    flash[:success] = t('save_success') unless @product_code.product_items.include?(@product_item)
  end


  private
  def product_code_params
    params.require(:product_code).permit(
        :code,
        :price,
        :cost,
        :status,
        :product_pack_id,
        :remarks,
        :myc_program_id
    )
  end
end

app/controllers/hq/product_items_controller.rb
class Hq::ProductItemsController < ApplicationController
  def index
  end

  def index_data
    respond_to do |format|
      format.json { render json: ProductItemDatatable.new(view_context) }
    end
  end


  def new
    @product_item = ProductItem.new
    @product_item.quantity_trigger_alert = 0
  end

  def create
    @product_item = ProductItem.new(product_item_params)

    if @product_item.save
      flash[:success] = t('save_success')
      redirect_to action: 'index'
    else
      flash[:error] = t('save_fail')
      render 'new'
    end
  end

  def edit
    @product_item = ProductItem.find(params[:id])
  end

  def update
    @product_item = ProductItem.find(params[:id])

    if @product_item.update(product_item_params)
      flash[:success] = t('save_success')
      redirect_to action: 'index'
    else
      flash[:error] = t('save_fail')
      render 'edit'
    end
  end

  private
  def product_item_params
    params.require(:product_item).permit(
        :description,
        :cost,
        :quantity_on_hand,
        :quantity_trigger_alert,
        :remarks,
        :status)
  end
end

app/controllers/hq/product_packs_controller.rb
class Hq::ProductPacksController < ApplicationController
  def index
  end

  def index_data
    respond_to do |format|
      format.json { render json: ProductPackDatatable.new(view_context) }
    end
  end

  def item_data_by_pack
    respond_to do |format|
      format.json { render json: ProductItemByPackDatatable.new(view_context, {product_pack_id: params[:id]}) }
    end
  end

  def new
    @product_pack = ProductPack.new
  end

  def create
    @product_pack = ProductPack.new(product_pack_params)

    if @product_pack.save
      flash[:success] = t('save_success')
      redirect_to "/hq/product_packs/#{@product_pack.id}/edit"
    else
      flash[:error] = t('save_fail')
      render 'new'
    end
  end

  def edit
    @product_pack = ProductPack.find(params[:id])
    @cost = ProductPack.cost(params[:id])
  end

  def update
    @product_pack = ProductPack.find(params[:id])
    @cost = ProductPack.cost(params[:id])

    if @product_pack.update(product_pack_params)
      flash[:success] = t('save_success')
      redirect_to action: 'index'
    else
      flash[:error] = t('save_fail')
      render 'edit'
    end
  end

  def select_item
    @product_pack_id = params[:id]
  end

  def add_item
    if params[:product_item_id].blank?
      @product_item = ProductItem.new
      @product_item.errors[:base] << t('product_item_cannot_be_empty')
    else
      @product_pack = ProductPack.find(params[:id])
      @product_item = ProductItem.find(params[:product_item_id])
      if @product_pack.product_items.include?(@product_item)
        @product_item.errors[:base] << t('product_item_already_exists')
      else
        @product_pack.product_items << @product_item
        @cost = ProductPack.cost(params[:id])
        flash[:success] = t('save_success')
      end
    end
  end

  def remove_item_confirm
    @product_pack_id = params[:id]
    @product_item_id = params[:product_item_id]
  end

  def remove_item
    @product_pack = ProductPack.find(params[:id])
    @product_item = ProductItem.find(params[:product_item_id])
    @product_pack.product_items.delete(@product_item)
    @cost = ProductPack.cost(params[:id])
    flash[:success] = t('save_success') unless @product_pack.product_items.include?(@product_item)
  end


  private
  def product_pack_params
    params.require(:product_pack).permit(
        :description,
        :status,
        :product_item_id
    )
  end
end

app/controllers/hq/student_reports_controller.rb
class Hq::StudentReportsController < ApplicationController
  def index
  end

  def index_data
    respond_to do |format|
      format.json { render json: StudentReportDatatable.new(view_context) }
    end
  end

  def index_total_data
    studio_id = params['columns']['0']['search']['value']
    teacher_id = params['columns']['1']['search']['value']
    respond_to do |format|
      format.json { render json: StudentReportTotalDatatable.new(view_context, {studio_id: studio_id, teacher_id: teacher_id}) }
    end
  end

  def generate

    return flash[:warning] = I18n.t('generate_no_data') if StudentReport.reports == 0

    @student_report = StudentReport.generate
    flash[:success] = I18n.t('generate_success') if @student_report.errors.count == 0
  end
end

app/controllers/hq/studios_controller.rb
class Hq::StudiosController < ApplicationController
	layout "application"

  def index

  end

  def data
    respond_to do |format|
      format.html
      format.json { render json: StudioDatatable.new(view_context) }
    end  
  end

  def new
    @studio = Studio.new
  end

  def create
      @studio = Studio.new(studio_params)

    if @studio.save
      flash[:success] = t('save_success')
      redirect_to(:action => 'index')
    else
      flash[:error] = t('save_fail')
      render('new')
    end

  end


  def edit
    @studio = Studio.find(params[:id])
  end

  def update
    @studio = Studio.find(params[:id])

    if @studio.update(studio_params)
      flash[:success] = t('save_success')
      redirect_to(:action => 'index')
    else
      flash[:error] = t('save_fail')
      render('edit')
    end
  end

  private
  def studio_params
    params.require(:studio).permit(:studio_name, :studio_code, :address, :post_code, :company_name, :company_registration_no, :phone_no, :email, :facebook_address, :website_address, :status)
  end


end

app/helpers/hq/families_helper.rb
module Hq::FamiliesHelper
end

app/helpers/hq/myc_programs_helper.rb
module Hq::MycProgramsHelper
end

app/helpers/hq/product_codes_helper.rb
module Hq::ProductCodesHelper
end

app/helpers/hq/product_items_helper.rb
module Hq::ProductItemsHelper
end

app/helpers/hq/product_packs_helper.rb
module Hq::ProductPacksHelper
end

app/helpers/hq/student_reports_helper.rb
module Hq::StudentReportsHelper
end

app/helpers/hq/students_helper.rb
module Hq::StudentsHelper
end

app/helpers/hq/studio_admins_helper.rb
module Hq::StudioAdminsHelper
end

app/helpers/hq/studio_helper.rb
module Hq::StudioHelper
end

app/helpers/hq/teachers_helper.rb
module Hq::TeachersHelper
end

app/views/hq/product_codes/_form.html.erb
<%= javascript_tag do %>

    $(document).ready(function() {
      var validator = $("#form_id").validate(setHighlight());
      validator.element('#product_code_code');
      validator.element('#product_code_status');
      validator.element('#product_code_price');
      validator.element('#product_code_myc_program_id');
    });

<% end %>

<%= error_messages_for(@product_code) %>

<div style="float: right; padding-top: 20px">
  <%= link_to "Cancel", {:action => :index}, :class => "btn btn-w-m btn-default" %>
  <%= f.submit 'Save', :class => 'btn btn-w-m btn-success' %>
</div>

<div class="clearfix"></div>

<div>
  <hr>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :code, "Code" %>
      <%= f.text_field :code, class: "form-control", required: "required" %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :status, "Status" %>
      <%= f.select :status, options_for_select(ProductCode.statuses.map { |s| [s[0].humanize, s[0]] }, selected: @product_code.status), {} , class: "form-control" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
      <label class="control-label">Cost</label>
      <input type="text" class="form-control" id="cost" value="<%= @cost %>" disabled>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :price, "Price" %>
      <%= f.text_field :price, class: "form-control", required: "required" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :remarks, "Remarks" %>
      <%= f.text_field :remarks, class: "form-control" %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :myc_program_id, "MYC Program" %>
      <%= f.select :myc_program_id, options_from_collection_for_select(@myc_program_select_options, 'id', 'program_name', selected: @product_code.myc_program_id), {}, class: "form-control", required: "required" %>
    </div>
  </div>
</div>

app/views/hq/product_codes/_remove_item_confirm.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="exampleModalLabel">Confirmation</h4>
</div>
<div class="modal-body">
  <div id="error-div"></div>
  Remove ?
</div>
<div class="modal-footer">
  <%= link_to 'No', '#', class: 'btn btn-default', data: {dismiss: 'modal'} %>
  <%= link_to 'Remove', "/hq/product_codes/#{@product_code_id}/remove_item/#{@product_item_id}", remote: true, method: :delete, class: 'btn btn-danger' %>
</div>

app/views/hq/product_codes/_remove_pack_confirm.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="exampleModalLabel">Confirmation</h4>
</div>
<div class="modal-body">
  <div id="error-div"></div>
  Remove ?
</div>
<div class="modal-footer">
  <%= link_to 'No', '#', class: 'btn btn-default', data: {dismiss: 'modal'} %>
  <%= link_to 'Remove', "/hq/product_codes/#{@product_code_id}/remove_pack/#{@product_pack_id}", remote: true, method: :delete, class: 'btn btn-danger' %>
</div>

app/views/hq/product_codes/add_item.js.erb
<%= render 'save_item' %>

app/views/hq/product_codes/add_pack.js.erb
<%= render 'save_pack' %>

app/views/hq/product_codes/edit.html.erb
<%= javascript_tag do %>

    $(document).ready(function() {
      initTableWithFirstColumnActionMenu('table-pack', false, 1, 'desc');
      initTableWithFirstColumnActionMenu('table-code', false, 1, 'desc');
    });

<% end %>

<% @breadcrumb = link_to('Product Codes', {:action => 'index'}) + " / " + "<b>Edit</b>".html_safe %>

<%= form_for @product_code, url: {:action => 'update', :id => @product_code.id}, :html => {:id => 'form_id'} do |f| %>

  <%= render(:partial => "form", :locals => {:f => f}) %>


    <%= link_to "Add pack", "/hq/product_codes/#{@product_code.id}/select_pack", remote: true, class: "btn btn-primary" %>

    <div class="clearfix"></div>

    </br>

    <div>
      <table id="table-pack" data-source="<%= "/hq/product_codes/#{@product_code.id}/pack_data_by_code.json" %>" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th></th>
          <th>Product Packs</th>
          <th>Cost</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>

    <%= link_to "Add item", "/hq/product_codes/#{@product_code.id}/select_item", remote: true, class: "btn btn-primary" %>

    <div class="clearfix"></div>

    </br>

    <div>
      <table id="table-code" data-source="<%= "/hq/product_codes/#{@product_code.id}/item_data_by_code.json" %>" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th></th>
          <th>Product Items</th>
          <th>Cost</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>

    <div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
      <div class="modal-dialog" role="document" display="table">
        <div id="modal-content" class="modal-content">
        </div>
      </div>
    </div>


<% end %>

app/views/hq/product_codes/index.html.erb
<%= javascript_tag do %>

    var tableId = 'table';

    $(document).ready(function() {
      initTableWithDeferLoading(tableId, true, 6, 'asc');
      filterData();
    });

    function initTableWithDeferLoading(tableId, enableFeatures, order_by_column_number, order_by_asc_or_desc) {
      dataTable = $('#' + tableId).DataTable({
      processing: true,
      serverSide: true,
      deferLoading: true,
      ajax: {
      "url": $('#' + tableId).data('source'),
      "type": "POST"
      },
      pagingType: 'full_numbers',
      order: [[order_by_column_number, order_by_asc_or_desc]],
      ordering:   enableFeatures,
      paging:   enableFeatures,
      info:   enableFeatures,
      bFilter: enableFeatures,
      pageLength: 100
      });

      return dataTable;
    }


    function filterData()
    {
      var statusId = $('#status-select').val();
      var dataTable = $('#' + tableId).DataTable();
      dataTable.columns('5:visIdx').search(statusId).draw();
    }
<% end %>

<% @breadcrumb = "Product Codes" %>

<div style="float: left; padding-top: 20px">
  <a href="#filter" class="btn btn-default" data-toggle="collapse">Filter</a>
</div>

<div style="float: right; padding-top: 20px">
  <a href="/hq/product_codes/new" , class="btn btn-success">New</a>
</div>

<div class="clearfix"></div>

<hr>

<div id="filter" class="collapse">
  <div class="row">
    <div class="col-sm-4">
      <div class="form-group">
        Status
        <select id="status-select" class="form-control">
          <option value=""></option>
          <% ProductCode.statuses.each do |status| %>
              <option value=<%= status[1] %> <%= 'selected=selected' if status[1] == ProductCode.statuses[:active] %> ><%= status[0].humanize %></option>
          <% end %>
        </select>
      </div>
    </div>
  </div>
  <button id="btnFilter" class="btn btn-primary inline" onclick="filterData()">Search</button>
  <hr>
</div>

<div>
  <table id="table" data-source="<%= index_data_hq_product_codes_path(format: :json) %>" class="table table-bordered table-striped">
    <thead>
    <tr>
      <th>Program Name</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Price</th>
      <th>Remarks</th>
      <th>Status</th>
      <th>Display Order</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/hq/product_codes/new.html.erb
<% @breadcrumb = link_to('Product Codes', {:action => 'index'}) + " / " + "<b>New</b>".html_safe %>

<%= form_for @product_code, url: {:action => 'create'}, :html => {:id => 'form_id'} do |f| %>

  <%= render(:partial => "form", :locals => {:f => f}) %>

<% end %>

app/views/hq/product_codes/remove_item.js.erb
<%= render 'save_item' %>

app/views/hq/product_codes/remove_item_confirm.js.erb
$("#modal-content").html("<%= j render('remove_item_confirm') %>")
$("#modal").modal("show")

app/views/hq/product_codes/remove_pack_confirm.js.erb
$("#modal-content").html("<%= j render('remove_pack_confirm') %>")
$("#modal").modal("show")

app/views/hq/product_codes/select_item.js.erb
$("#modal-content").html("<%= j render 'select_item' %>")
$("#modal").modal("show")

$(document).ready(function() {
  var validator = $("#form_id_select_item").validate(setHighlight());
  validator.element('#product_item_id');
});

app/views/hq/product_codes/select_pack.js.erb
$("#modal-content").html("<%= j render 'select_pack' %>")
$("#modal").modal("show")
$(document).ready(function() {
  var validator = $('#form_id_select_pack').validate(setHighlight());
  validator.element('#product_pack_id');
});

app/views/hq/product_codes/show_pack_items.js.erb
$("#modal-content").html("<%= j render('show_pack_items') %>")
$("#modal").modal("show")
$(document).ready(function() {
  initTableWithFirstColumnActionMenu('table-pack-items', false, 1, 'asc');
});